<?php
/**
 * @file
 * Theme file.
 *
 * All preprocessors and theme functions goes here.
 */

/**
 * Implements hook_preprocess_page().
 *
 * @see page.html.twig
 */
function stanisavljevic_preprocess_page(&$variables) {
  $theme = 'stanisavljevic';
  // Add content for home page regions.
  $home_page_regions = array (
    'content_light_blue',
    'footer_menu',
    'footer_social',
  );

  $variables['snippet'] = _mbase_smart_render($home_page_regions, $theme);
}
